# Generated by Django 5.1.4 on 2024-12-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('bio', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/images/actors/')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movie.country')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('imdb_rank', models.IntegerField(default=251)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/movie/')),
                ('Languages', models.ManyToManyField(related_name='movies', to='movie.language')),
                ('actors', models.ManyToManyField(related_name='movies', to='movie.actor')),
                ('countries', models.ManyToManyField(related_name='movies', to='movie.country')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/video/')),
                ('quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '2160p'), ('4320p', '4320p'), ('720p-10bit', '720p-10bit'), ('1080p-10bit', '1080p-10bit'), ('1440p-10bit', '1440p-10bit'), ('2160p-10bit', '2160p-10bit'), ('4320p-10bit', '4320p-10bit'), ('144p-256', '144p-256'), ('240p-256', '240p-256'), ('360p-256', '360p-256'), ('480p-256', '480p-256'), ('720p-256', '720p-256'), ('1080p-256', '1080p-256'), ('1440p-256', '1440p-256'), ('2160p-256', '2160p-256'), ('4320p-256', '4320p-256')], max_length=20)),
                ('download_url', models.TextField(blank=True, null=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_urls', to='movie.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_urls', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('seasons', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('imdb_rank', models.IntegerField(default=251)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/series')),
                ('Languages', models.ManyToManyField(related_name='series', to='movie.language')),
                ('actors', models.ManyToManyField(related_name='series', to='movie.actor')),
                ('countries', models.ManyToManyField(related_name='series', to='movie.country')),
                ('genre', models.ManyToManyField(related_name='series', to='movie.genre')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.series'),
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('upload_date', models.DateField()),
                ('season', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailer', to='movie.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailer', to='movie.series')),
            ],
        ),
    ]
