# Generated by Django 5.1.4 on 2024-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='release_year',
        ),
        migrations.RemoveField(
            model_name='series',
            name='release_date',
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
