# Generated by Django 5.1.4 on 2024-12-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_languages_movie_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='Languages',
            new_name='languages',
        ),
    ]
