# Generated by Django 5.1.4 on 2024-12-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_languages_series_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='series',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='downloadurl',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='downloadurl',
            name='movie',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episode_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='season',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='series',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movie.movie'),
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/video/')),
                ('quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '2160p'), ('4320p', '4320p'), ('720p-10bit', '720p-10bit'), ('1080p-10bit', '1080p-10bit'), ('1440p-10bit', '1440p-10bit'), ('2160p-10bit', '2160p-10bit'), ('4320p-10bit', '4320p-10bit'), ('144p-256', '144p-256'), ('240p-256', '240p-256'), ('360p-256', '360p-256'), ('480p-256', '480p-256'), ('720p-256', '720p-256'), ('1080p-256', '1080p-256'), ('1440p-256', '1440p-256'), ('2160p-256', '2160p-256'), ('4320p-256', '4320p-256')], max_length=20)),
                ('download_url', models.TextField(blank=True, null=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_urls', to='movie.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_urls', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('avg_duration', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('description', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.series')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='series_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movie.season'),
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('file', models.FileField(upload_to='media/subtitles/')),
                ('download_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movie.downloadfile')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtitles', to='movie.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='DownloadURL',
        ),
    ]
