# Generated by Django 5.1.4 on 2024-12-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_rename_genre_series_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='user_rating',
        ),
    ]
