# Generated by Django 5.1.4 on 2025-01-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_movie_user_rating_remove_series_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='end_date',
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='file_format',
            field=models.CharField(choices=[('MP4', 'MP4'), ('FLV', 'FLV'), ('MOV', 'MOV'), ('MKV', 'MKV'), ('LXF', 'LXF'), ('MXF', 'MXF'), ('AVI', 'AVI'), ('QuickTime', 'QuickTime'), ('WebM', 'WebM')], default='MP4', help_text='File container format.', max_length=20),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='source',
            field=models.CharField(choices=[('WEB-DL', 'WEB-DL'), ('WEBRip', 'WEBRip'), ('Blu-ray', 'Blu-ray'), ('BRRip', 'BRRip'), ('HDRip', 'HDRip'), ('DVD-Rip', 'DVD-Rip'), ('CAM', 'CAM'), ('TS', 'TS'), ('HDTV', 'HDTV')], default='WEB-DL', help_text='Source of the video file.', max_length=20),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='sticky_subtitles',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='age_category',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='age_category',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='media/trailers/'),
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='file',
            field=models.FileField(upload_to='media/videos/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/series/'),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'Actor'), ('D', 'Director'), ('W', 'Writer'), ('O', 'Other')], max_length=1)),
                ('bio', models.TextField()),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/crews/')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movie.country')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.crew'),
        ),
        migrations.AddField(
            model_name='series',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='series', to='movie.crew'),
        ),
    ]
