# Generated by Django 5.1.4 on 2025-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_series_end_date_downloadfile_file_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
