# Generated by Django 5.1.4 on 2025-01-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_series_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='10-bit_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='256-bit-encryption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='quality',
            field=models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '2160p'), ('4320p', '4320p')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='source',
            field=models.CharField(choices=[('Blu-ray', 'Blu-ray'), ('WEB-DL', 'WEB-DL'), ('WEBRip', 'WEBRip'), ('HDRip', 'HDRip'), ('BRRip', 'BRRip'), ('HDTV', 'HDTV'), ('DVD-Rip', 'DVD-Rip'), ('TS', 'TS'), ('CAM', 'CAM')], default='WEB-DL', help_text='Source of the video file.', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_category',
            field=models.CharField(choices=[('G', 'General Audiences(G)'), ('PG', 'Parental Guidance Suggested(PG)'), ('PG-13', 'Parents Strongly Cautioned(PG-13)'), ('R', 'Restricted(R)'), ('NC-17', 'Adults Only(NC-17)')], max_length=5),
        ),
    ]
