# Generated by Django 5.1.4 on 2025-01-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_episode_subtitle_link_movie_subtitle_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadfile',
            old_name='10-bit_variant',
            new_name='10-bit-variant',
        ),
    ]
