# Generated by Django 5.1.4 on 2025-01-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_rename_10_bit_variant_downloadfile_10_bit_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='avg_duration',
        ),
    ]
