# Generated by Django 5.1.4 on 2025-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_remove_season_avg_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
