# Generated by Django 5.1.4 on 2025-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_season_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfile',
            name='file',
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
