# Generated by Django 5.1.4 on 2025-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_remove_downloadfile_file_downloadfile_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='trailer_video',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
