# Generated by Django 5.1.4 on 2025-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_remove_trailer_trailer_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='imdb_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
