# Generated by Django 5.1.4 on 2025-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_downloadfile_created_at_downloadfile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
