# Generated by Django 5.1.4 on 2025-01-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_season_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
