# Generated by Django 5.1.4 on 2025-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_remove_crew_birth_date_crew_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='choosen_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='choosen_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='choosen_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='choosen_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
