# Generated by Django 5.1.4 on 2025-01-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_movie_choosen_country_movie_choosen_home_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='trailer_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
